### ISSUE TITLE
Ошибка авторизации rutracker

### ISSUE THREAD

**Issue by Semihal** [andrey-yantsen/flexget-config#1]
Использую ваш скрипт и наткнулся на следующую проблему:

> 2019-03-31 16:50 CRITICAL plugin        new movies russian hd unable to obtain cookies from rutracker
> 2019-03-31 16:50 WARNING  task          new movies russian hd Aborting task (plugin: rutracker_auth)

Сначала подумал дело в доступности рутрекера на территории РФ, но нет, прокси не помогли.
Как такое пофиксить, есть идеи?

**Comment by andrey-yantsen** [comment]
Попробуйте последнюю версию flexget — там была проблема с тем, что использовалось старое зеркало.

**Comment by githubbla** [comment]
У меня такая же проблема, Flexget: 3.1.46 API: 1.7.1
что это может быть?

**Comment by andrey-yantsen** [comment]
@githubbla лучше спросите создателей Flexget: https://github.com/Flexget/Flexget, я уже больше года не пользуюсь rutracker'ом. Правда, вряд ли они не смогут помочь — сомневаюсь что из них кто-то пользуется русским трекером.

**Comment by githubbla** [comment]
спасибо, а чем пользуетесь?

**Comment by andrey-yantsen** [comment]
@githubbla https://rarbggo.org/

**Comment by githubbla** [comment]
спасибо, а есть для него конфигурация для flexget чтоб из него вытрушивать фильмы?

**Comment by andrey-yantsen** [comment]
@githubbla у меня там тупо идёт поиск по моему списку фильмов на trakt.tv (ну и на rarbg нет переводов на русский), вам такое подойдёт?

**Comment by githubbla** [comment]
Хотелось бы с русским, не с русским все намного проще...
может можно не логиниться в рутракер, и грузить через магнет линк, но я не знаю как это сделать :(
10 лет пользуюсь flexget а понять язык его конфигурации не в силах.



web_server:
  bind: 0.0.0.0
  port: 3539
  web_ui: yes

templates:
  global:
    retry_failed:
      retry_time: 10 seconds
      retry_time_multiplier: 6
      max_retries: 7

  transmissionrpc:
    transmission:
      host: 192.168.11.235
      port: 9091
      username: transmission
      password: transmission
      path: /downloads/RussianMovies/

  tvimdb:
    headers:
      User-Agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36'
    rutracker_auth:
      username: loginruauth
      password: 234nsdnfsdf
    manipulate:
      - title:
          replace:
            regexp: '\(custom\)'
            format: ''
      - title:
          extract: (/\s(?=[А-Яа-яA-Za-z0-9.,-][A-Za-z0-9.,-])(.*))|(/\s(?=[A-Za-z0-9]\s)(.*))
          replace:
            regexp: '\((.+)\)\s\[(?=\d\d\d\d)'
            format: '/ '
      - title:
          replace:
            regexp: '^/\s'
            format: ''
      - title:
          extract: (.*)(?=\]\s)
          replace:
            regexp: '\s\s'
            format: ' '
      - title:
          extract: (.*)(?=\))
          replace:
            regexp: '(?<![а-яA-Za-zА-Я])\,'
            format: ''
      - title:
          replace:
            regexp: '\](.*)'
            format: ''
      - title:
          replace:
            regexp: '\s\(\s'
            format: ' '
      - title:
          replace:
            regexp: '&#039;'
            format: '’'
    regexp:
      reject:
        - hindi
        - german   
      reject_excluding:
        - DVDRip|HDRip|BDRip|WebDl|WEB-DLRip-AVC|WEB-DLRip|WEB-DL|BDRip|TVRip|SATRip|WEB-DLRip|HD
    content_filter:
      reject:
        - '*.rar'
        - '*.iso'
        - '*.wmv'
    imdb:
      min_score: 5.9
      min_year: 2018
      reject_genres:
        - horror
    seen_movies: strict 
    set:
      content_filename: "{{ imdb_name }} ({{ imdb_year }}) - {{ quality|upper }}"


  tvrus:
    headers:
      User-Agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36'
    rutracker_auth:
      username: loginruau
      password: 45454dfd
    manipulate:
      - title:
          replace:
            regexp: '\(custom\)'
            format: ''
      - title:
          extract: (/\s(?=[А-Яа-яA-Za-z0-9.,-][A-Za-z0-9.,-])(.*))|(/\s(?=[A-Za-z0-9]\s)(.*))
          replace:
            regexp: '\((.+)\)\s\[(?=\d\d\d\d)'
            format: '/ '
      - title:
          replace:
            regexp: '^/\s'
            format: ''
      - title:
          extract: (.*)(?=\]\s)
          replace:
            regexp: '\s\s'
            format: ' '
      - title:
          extract: (.*)(?=\))
          replace:
            regexp: '(?<![а-яA-Za-zА-Я])\,'
            format: ''
      - title:
          replace:
            regexp: '\](.*)'
            format: ''
      - title:
          replace:
            regexp: '\s\(\s'
            format: ' '
      - title:
          replace:
            regexp: '&#039;'
            format: '’'
    regexp:
      reject:
        - hindi
        - german      
      reject_excluding:
        - DVDRip|HDRip|BDRip|WebDl|WEB-DLRip-AVC|WEB-DLRip|WEB-DL|BDRip|TVRip|SATRip|WEB-DLRip|HD
    content_filter:
      reject:
        - '*.rar'
        - '*.iso'
        - '*.wmv'
    imdb:
      min_score: 5.9
      min_year: 2018
    seen_movies: strict 
    set:
      content_filename: "{{ imdb_name }} ({{ imdb_year }}) - {{ quality|upper }}"
    
  movies:
    imdb:
      min_score: 5.9
      min_year: 2018
    content_filter:
      reject:
        - '*.rar'
        - '*.iso'
        - '*.wmv'
    content_size:
      min: 630
    regexp:
      reject:
        - hindi
        - german
      reject_excluding:
        - 1080p
        - 720p
    set:
      content_filename: "{{ imdb_name }} ({{ imdb_year }}) - {{ quality|upper }}"


  movie-search-and-add:
    priority: 10 # run after the movie queue fill task
    discover:
      what:
        - movie_list: l1
      from:
        - search_rss: https://yts.am/rss/{{search_term|replace("%20%28","")|replace("%29%20","")|replace("0","")|replace("1","")|replace("2","")|replace("3","")|replace("4","")|replace("5","")|replace("6","")|replace("7","")|replace("8","")|replace("9","")|replace("%","_")}}/all/all/0
    list_match:
      from:
        - movie_list: 
            list_name: l1
    accept_all: yes


tasks:
  rutrackereng:
    imdb_lookup: yes
    set:
      filename: "{{ imdb_name }} ({{ imdb_year }}) - {{ quality|upper }}"
    template: 
      - tvimdb
      - transmissionrpc
    notify:
      task:
        template: html-downloaded  # Optional, if you want html instead of plain text
        via:
          - email:
              from: films@****.com
              to: 
                - ****@****.org
                - ***@***.org
              html: yes
              smtp_host: smtp.gmail.com
              smtp_port: 587
              smtp_username: ****@****.org
              smtp_password: ****
              smtp_tls: yes
    inputs:
      - rss: http://feed.rutracker.org/atom/f/930.atom
      - rss: http://feed.rutracker.org/atom/f/209.atom
      - rss: http://feed.rutracker.org/atom/f/2093.atom
      - rss: http://feed.rutracker.org/atom/f/2200.atom
      - rss: http://feed.rutracker.org/atom/f/7.atom

  ytg:
    imdb_lookup: yes
    set:
      content_filename: "{{ imdb_name }} ({{ imdb_year }}) - {{ quality|upper }}"
    template: 
      - movies
      - transmissionrpc
    transmission:
      path: /downloads/EnglishMovies/
    notify:
      task:
        template: html-downloaded  # Optional, if you want html instead of plain text
        via:
          - email:
              from: films@****.org
              to: 
                - **@***.org
                - **@***.org
              html: yes
              smtp_host: smtp.gmail.com
              smtp_port: 587
              smtp_username: fil***ms@****.org
              smtp_password: ****
              smtp_tls: yes
    inputs:
      - rss: https://yts.ag/rss/0/720p/family/7
      - rss: https://yts.ag/rss/0/720p/family/5
      - rss: https://yts.ag/rss/0/720p/adventure/5
      - rss: https://yts.ag/rss/0/720p/adventure/7
      - rss: https://yts.ag/rss/0/720p/comedy/5
      - rss: https://yts.ag/rss/0/720p/comedy/7
      - rss: https://yts.ag/rss/0/720p/animation/5
      - rss: https://yts.ag/rss/0/720p/animation/7
      - rss: https://yts.ag/rss/0/720p/action/5
      - rss: https://yts.ag/rss/0/720p/action/7
      - rss: https://yts.ag/rss/0/720p/crime/5
      - rss: https://yts.ag/rss/0/720p/crime/7
      - rss: https://yts.ag/rss/0/720p/fantasy/5
      - rss: https://yts.ag/rss/0/720p/fantasy/7
      - rss: https://yts.ag/rss/0/720p/history/5
      - rss: https://yts.ag/rss/0/720p/history/7
      - rss: https://yts.ag/rss/0/720p/romance/5
      - rss: https://yts.ag/rss/0/720p/romance/7
      - rss: https://yts.ag/rss/0/720p/drama/5
      - rss: https://yts.ag/rss/0/720p/drama/7
      - rss: https://yts.ag/rss/0/720p/western/5
      - rss: https://yts.ag/rss/0/720p/western/7
      - rss: https://yts.ag/rss/0/720p/all/8
      - rss: https://yts.ag/rss/0/720p/all/9

  updateMovieList:
    priority: 1 # run before all
    imdb_watchlist:
      user_id: ur2657
      list: watchlist
    accept_all: yes
    list_add:
      - movie_list: l1  

     
      
  mylist:
    imdb_lookup: yes
    regexp:
      reject_excluding:
        - 1080p
    set:
      content_filename: "{{ imdb_name }} ({{ imdb_year }}) - {{ quality|upper }}"
    template: 
      - movie-search-and-add
      - transmissionrpc
    imdb:
      min_year: 2018
    transmission:
      path: /downloads/EnglishMovies/
    notify:
      task:
        template: html-downloaded  # Optional, if you want html instead of plain text
        via:
          - email:
              from: films3434@***.org
              to: 
                - ***@***.org
                - ***@****.org
              html: yes
              smtp_host: smtp.gmail.com
              smtp_port: 587
              smtp_username: *****
              smtp_password: ****
              smtp_tls: yes


#  remove-stale-torrents:
#    from_transmission:
#      only_complete: yes
#    disable: [seen, seen_info_hash]
#    if:
#      - transmission_progress == 100: accept
#      - not transmission_seed_ratio_ok: reject
#      - not transmission_idle_limit_ok: reject
#    transmission:
#    action: purge

schedules:
  # Run every task once an hour
  - tasks: '*'
    interval:
      hours: 4
